dist: xenial

addons:
  apt:
    packages:
      - rabbitmq-server

language: python

matrix:
  include:
    - python: 3.8
      env: TOX_ENV=py38
    - python: 3.9
      env: TOX_ENV=py39
    - python: 3.9
      env: TOX_ENV=docs
    - python: 3.9
      env: TOX_ENV=pep8

# Install the test runner.
install: pip install tox
script: tox -e $TOX_ENV

# Control the branches that get built.
branches:
  only:
    - master
